// modal
export const SET_IS_SHOW_MODAL_TRUE = "SET_IS_SHOW_MODAL_TRUE";
export const SET_IS_SHOW_MODAL_FALSE = "SET_IS_SHOW_MODAL_FALSE";
// popup modal
export const SET_IS_SHOW_POPUP_MODAL_TRUE = "SET_IS_SHOW_POPUP_MODAL_TRUE";
export const SET_IS_SHOW_POPUP_MODAL_FALSE = "SET_IS_SHOW_POPUP_MODAL_FALSE";
// albums
export const SET_ALBUMS = "SET_ALBUMS";
// album
export const SET_ALBUM_PARAMS_TITLE = "SET_ALBUM_PARAMS_TITLE";
export const SET_ALBUM_PARAMS_USER_ID = "SET_ALBUM_PARAMS_USER_ID";
export const RESET_ALBUM_PARAMS = "RESET_ALBUM_PARAMS";
export const SET_ALBUM_PARAMS_ID = "SET_ALBUM_PARAMS_ID";
// search
export const SET_SEARCH_ID = "SET_SEARCH_ID";
