// modal
export const SET_IS_SHOW_MODAL_TRUE = "SET_IS_SHOW_MODAL_TRUE";
export const SET_IS_SHOW_MODAL_FALSE = "SET_IS_SHOW_MODAL_FALSE";
// popup modal
export const SET_IS_SHOW_POPUP_MODAL_TRUE = "SET_IS_SHOW_POPUP_MODAL_TRUE";
export const SET_IS_SHOW_POPUP_MODAL_FALSE = "SET_IS_SHOW_POPUP_MODAL_FALSE";
// albums
export const SET_ALBUMS = "SET_ALBUMS";
